version: '3'

services:
  be_boilerplate:
    deploy:
      resources:
        limits:
          cpus: '0.90'
          # memory: 400M
    command: npm start
    ports:
      - '80:4000'
    env_file:
      - ./config/prod.env
